// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyxvl3XwEJTXpHl6P86mEUl9D8eJfw04U',
    appId: '1:705674124888:web:9d496b54bb8de780db742d',
    messagingSenderId: '705674124888',
    projectId: 'carpool-fc576',
    authDomain: 'carpool-fc576.firebaseapp.com',
    storageBucket: 'carpool-fc576.firebasestorage.app',
    measurementId: 'G-6HF8RZHE86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwA7yi1iAjF_PH5zOEq8269ZdiLrb-7bc',
    appId: '1:705674124888:android:07ae62101d7ec31ddb742d',
    messagingSenderId: '705674124888',
    projectId: 'carpool-fc576',
    storageBucket: 'carpool-fc576.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL76PfqPL0ortzu5hK6ehygTXTbDH0O3Q',
    appId: '1:705674124888:ios:bac8df0f118dad0adb742d',
    messagingSenderId: '705674124888',
    projectId: 'carpool-fc576',
    storageBucket: 'carpool-fc576.firebasestorage.app',
    iosBundleId: 'com.example.carPool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL76PfqPL0ortzu5hK6ehygTXTbDH0O3Q',
    appId: '1:705674124888:ios:bac8df0f118dad0adb742d',
    messagingSenderId: '705674124888',
    projectId: 'carpool-fc576',
    storageBucket: 'carpool-fc576.firebasestorage.app',
    iosBundleId: 'com.example.carPool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyxvl3XwEJTXpHl6P86mEUl9D8eJfw04U',
    appId: '1:705674124888:web:11c3c492f3bf25f9db742d',
    messagingSenderId: '705674124888',
    projectId: 'carpool-fc576',
    authDomain: 'carpool-fc576.firebaseapp.com',
    storageBucket: 'carpool-fc576.firebasestorage.app',
    measurementId: 'G-MFTQLKCL4B',
  );
}
